angular.module('app').controller 'SalesTabCtrl', ($scope, $mdDialog, SaleService, $state, ReportsService) ->
  $scope.toggleSearch = false
  #$scope.report_url = null;
  $scope.headers = [
    {
      name: 'Fecha'
      field: 'sale.created_at'
    }
    {
      name: 'Comprador'
      field: 'sale.buyer.first_name + \' \' + sale.buyer.last_name'
    }
    {
      name: 'Total Gramos Finos'
      field: 'sale.fine_grams.toFixed(3)'
    }
    {
      name: 'Precio venta'
      field: 'sale.price.toFixed(3)'
    }
    {
      name: 'Precio compra'
      field: 'sale.purchases_total_value.toFixed(3)'
    }
    {
      name: 'Ganancia'
      field: 'sale.total_gain.toFixed(3)'
    }
    {
      name: 'Tipo de Mineral'
      field: 'sale.mineral_type'
    }
    {
      name: 'Estado'
      field: 'sale.transaction_state'
    }
  ]
  $scope.pages = 0
  $scope.currentPage = 1

  #Sale service call to api to retrieve all sales for current user
  SaleService.all_paged().success((sales, status, headers, config) ->
    $scope.pages = parseInt(headers().total_pages)
    $scope.count = sales.length
    $scope.sales = sales
  ).error (data, status, headers, config) ->
    $scope.infoAlert 'ERROR', 'No se pudo realizar la solicitud'

  # Deprecated: because I will avoid save important thing is session but the id
  $scope.showSale = (sale) ->
    SaleService.model = sale
    SaleService.saveState()
    $state.go 'inventory.sale_details'
    return

  $scope.goOrderDetails = (orderId) ->
    $state.go('inventory.sale_details', {id: orderId})

  $scope.infoAlert = (title, content) ->
    $mdDialog.show $mdDialog.alert().title(title).content(content).ok('OK')
    return

  $scope.generateReport = (sale) ->
    ReportsService.generateTransactionMovements(sale.id).success((data) ->
      sale.report_url = data.base_file_url
      $scope.infoAlert 'Reporte Tributario', 'El archivo plano CSV se generó satisfactoriamente con los movimientos contables de la transacción'
    ).error (data) ->
      $scope.infoAlert 'ERROR', 'No se pudo generar y descargar el Archivo con los movimientos de la transacción'
    return

  return

# ---
# generated by js2coffee 2.2.0