---
http_interactions:
- request:
    method: post
    uri: http://127.0.0.1:8910/session
    body:
      encoding: UTF-8
      string: '{"desiredCapabilities":{"browserName":"phantomjs","version":"","platform":"ANY","javascriptEnabled":true,"cssSelectorsEnabled":true,"takesScreenshot":true,"nativeEvents":false,"rotatable":false}}'
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json; charset=utf-8
      Content-Length:
      - '195'
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache:
      - no-cache
      Content-Length:
      - '534'
      Content-Type:
      - application/json;charset=UTF-8
    body:
      encoding: UTF-8
      string: '{"sessionId":"231709f0-963e-11e6-a1a8-4ffdca11cb18","status":0,"value":{"browserName":"phantomjs","version":"1.9.7","driverName":"ghostdriver","driverVersion":"1.1.0","platform":"mac-unknown-32bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}}'
    http_version: 
  recorded_at: Wed, 19 Oct 2016 20:53:50 GMT
- request:
    method: delete
    uri: http://127.0.0.1:8910/session/231709f0-963e-11e6-a1a8-4ffdca11cb18
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache:
      - no-cache
      Content-Length:
      - '74'
      Content-Type:
      - application/json;charset=UTF-8
    body:
      encoding: UTF-8
      string: '{"sessionId":"231709f0-963e-11e6-a1a8-4ffdca11cb18","status":0,"value":{}}'
    http_version: 
  recorded_at: Wed, 19 Oct 2016 20:53:50 GMT
- request:
    method: get
    uri: http://127.0.0.1:8910/shutdown
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache:
      - no-cache
      Content-Length:
      - '36'
      Content-Type:
      - text/html;charset=UTF-8
    body:
      encoding: UTF-8
      string: "<html><body>Closing...</body></html>"
    http_version: 
  recorded_at: Wed, 19 Oct 2016 20:53:50 GMT
recorded_with: VCR 3.0.3
